"""Update release actions table to contain deployment status, added unique constraints and a tag url column

Revision ID: 4be2150f205a
Revises: 327feae94d72
Create Date: 2024-06-01 18:11:50.706339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be2150f205a'
down_revision: Union[str, None] = '327feae94d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release_action_approvals')
    op.drop_table('release_actions')
    op.drop_table('releases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=127), nullable=False),
    sa.Column('state', sa.VARCHAR(length=8), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('release_actions',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('release_id', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=127), nullable=False),
    sa.Column('version', sa.VARCHAR(length=15), nullable=False),
    sa.Column('action_url', sa.VARCHAR(length=127), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_url'),
    sa.UniqueConstraint('version')
    )
    op.create_table('release_action_approvals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('release_action_id', sa.NUMERIC(), nullable=False),
    sa.Column('approved_by', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['release_action_id'], ['release_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
